name: gasdetector
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  firebase_auth: ^4.4.0
  flutter_native_splash: ^2.2.19
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.2.5
  firebase_database: ^10.1.0
  fl_chart: ^0.61.0
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo-color.png"
  min_sdk_android: 21

flutter_native_splash:
  image: images/logo-color.png
  color: "e6f4ff"
  
  android_12:
    image: images/logo-color.png
    color: "e6f4ff"

flutter:
  uses-material-design: true
